calibration_value_str: ((3**2+475**2)**(1/2))/28
calibration_value: 16.964624056776355
load_arr:
- 0
- 10
- 20
- 30
- 40
circle_radius: 35
red_thresh_high: 110
green_thresh_high: 110
blue_thresh_high: 110
grey_delta: 20
angle_tol: 10.0
min_cluster_size: 5
lower_green:
- 35
- 90
- 80
upper_green:
- 100
- 255
- 255
track_previous: false
max_marker_jump: 70.0
